# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b48f791dbb6287e45631ee2335dcc1e6178a10fb28072c54277167eb310064744128c64ed5fa57d7cc6c46a05ff084d795601a75628612090b51fe466c6766a5

test:
  secret_key_base: dd82cacf5898e20dae2f1613898c95f9e4384e5fb825ec901b3915ecf55152f35e10798df931996f6fd6666aa12ffdb2ee96f9319bc88dc9e07256207a22c03b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
